### ISSUE TITLE
我想问一下这个my-tree组件没有声明，引入main.js里面会报错

### ISSUE THREAD

**Issue by chantel186** [caihg/caihg#1]

**Comment by caihg** [comment]
@chantel186 
my-tree 被 main.vue 引用，main.vue 被 main.js 引用

**Comment by chantel186** [comment]
就是common里面没有my-tree.vue文件的啊

**Comment by chantel186** [comment]
这个my-tree组件是自己定义写的嘛？还是通过npm安装的

**Comment by caihg** [comment]
@chantel186 
就是 treeMenu.vue 文件，不过在引用时改了名 import myTree from './common/treeMenu.vue'

**Comment by chantel186** [comment]
喔喔，我试试，可以加个扣扣聊聊嘛？我是妹子，你呢？

**Comment by caihg** [comment]
@chantel186 
709800442
